apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
  selector:
    app.kubernetes.io/name: kafka
---
apiVersion: apps/v1
kind: Deploymebt
metadata:
  name: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /bin/sh
            - -c
            - bin/kafka-storage.sh format -t $CLUSTER_ID -c config/kraft/server.properties --ignore-formatted && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=${KAFKA_LISTENERS} --override inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME}
          env:
            - name: LOG_DIR
              value: /tmp/logs
            - name: CLUSTER_ID
              value: m1Ze6AjGRwqarkcxJscgyQ
            - name: KAFKA_LISTENERS
              value: LISTENER_INTERNAL://:9092,CONTROLLER://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: LISTENER_INTERNAL://kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: LISTENER_INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER_INTERNAL
          image: quay.io/strimzi/kafka:latest-kafka-3.2.0
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - netstat -lnt | grep -Eq 'tcp6?[[:space:]]+[0-9]+[[:space:]]+[0-9]+[[:space:]]+[^ ]+:9092.*LISTEN[[:space:]]'
            failureThreshold: 100
            initialDelaySeconds: 20
            periodSeconds: 1
            successThreshold: 1
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 0
      volumes:
        - emptyDir: {}
          name: tmp
