apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:15.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-env
          ports:
            - name: postgres
              containerPort: 5432
          startupProbe:
            exec:
              command: [/bin/sh, -c, exec pg_isready]
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 50
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: config
              mountPath: /docker-entrypoint-initdb.d/init.sh
              subPath: init.sh
              readOnly: true
            - name: data
              mountPath: /var/lib/postgresql
            - name: tmp
              mountPath: /var/run/postgresql
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: postgres-config
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
