resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: postgres-config
    files:
      - files/init.sh

secretGenerator:
  - name: postgres-env
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
